---
apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Pod
    metadata:
      labels:
        app: vitess
        cell: uswest1
        component: vtctld
      name: vtctld-example-000000000
      namespace: default
    spec:
      containers:
      - command:
        - /bin/bash
        - -c
        - '/vt/bin/vtctld -grpc_port 15999 -service_map ''grpc-vtctl'' -workflow_manager_init
          -workflow_manager_use_election -alsologtostderr -web_dir /vt/src/vitess.io/vitess/web/vtctld
          -web_dir2 /vt/src/vitess.io/vitess/web/vtctld2/app -log_dir /vt/tmp -topo_implementation
          etcd2 -cell uswest1 -port 15000 -topo_global_server_address etcd-cluster-client:2379
          -topo_global_root /vitess/global '
        image: vitess/base
        imagePullPolicy: Always
        name: vtctld
        ports:
        - containerPort: 15000
          name: web
          protocol: TCP
        - containerPort: 15999
          name: grpc
          protocol: TCP
        stdin: true
        tty: true
        volumeMounts:
        - mountPath: /dev/log
          name: syslog
        - mountPath: /etc/ssl/certs
          name: certs
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /dev/log
          type: ""
        name: syslog
      - hostPath:
          path: /etc/ssl/certs
          type: ""
        name: certs
  - apiVersion: v1
    kind: Service
    metadata:
      name: vtctld
      namespace: default
      labels:
        app: vitess
        cell: uswest1
        component: vtctld
    spec:
      ports:
        - name: web
          port: 15000
        - name: grpc
          port: 15999
      type: NodePort
      selector:
        app: vitess
        component: vtctld
      
